package com.v6ak.hagen.examples

import com.v6ak.hagen.expressions.Entity
import com.v6ak.hagen.expressions._

//noinspection TypeAnnotation
object DefinedItems:
  // Existing entities should be put there.
  // TODO: Something like this should be autogenerated from HA
  val rpiPowerStatus = Entity[Boolean]("binary_sensor.rpi_power_status")
  val fridgeHumiditySensor = Entity[Double]("sensor.fridge_humidity")
  val fridgeTemperatureSensor = Entity[Double]("sensor.fridge_temperature")

