name: Web deploy

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt test
      - name: Run Hagen
        run: sbt run
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: out

      - name: Archive artifact
        shell: bash
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "out" \
            -cvf "out.tar" \
            .
        env:
          INPUT_PATH: ${{ inputs.path }}
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: out.tar
          retention-days: 1

  deploy:
    needs: build

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
